services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mic-notificationservice:local
    restart: unless-stopped
    environment:
      PROFILE: local
      SERVER_PORT: 8080
      SSL_ENABLED: "false"
      POSTGRES_URL: jdbc:postgresql://host.docker.internal:5401/db01
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: pass01
      ISSUER_URI: http://localhost:6001
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: your-email@gmail.com
      MAIL_PASSWORD: your-app-password
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6002:8080"
