server:
  port: ${SERVER_PORT:6003}
  ssl:
    enabled: ${SSL_ENABLED:false}

spring:
  datasource:
    url: ${NTF_DATABASE_URL:jdbc:postgresql://localhost:5404/db04}
    username: ${NTF_DB_USER:user04}
    password: ${NTF_DB_PASSWORD:pass04}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
  mail:
    host: ${NTF_HOST_EMAIL}
    port: ${NTF_PORT_EMAIL}
    username: ${NTF_USER_EMAIL}
    password: ${NTF_PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${NFT_KAFKA_BOOTSTRAP_SERVERS:crossover.proxy.rlwy.net:32058}
    listener:
      auto-startup: false
    enabled: true
    consumer:
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9000}

logging:
  level:
    root: INFO
    com.backandwhite: DEBUG
    org.springframework.security: DEBUG
