spring:
  application:
    name: mic-notificationservice
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  banner:
    charset: UTF-8
  profiles:
    active: ${PROFILE:local}
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
